-- FreePepite : file d'attente des propositions
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.propositions (
  id bigint generated by default as identity primary key,
  titre text not null check (char_length(titre) between 1 and 100),
  texte text not null check (char_length(texte) between 1 and 4000),
  auteur text check (auteur is null or char_length(auteur) <= 50),
  statut text not null default 'en_attente' check (statut in ('en_attente','validee','refusee')),
  created_at timestamptz not null default now()
);

alter table public.propositions enable row level security;

-- Les visiteurs anonymes peuvent uniquement envoyer une proposition.
drop policy if exists "public_insert_propositions" on public.propositions;
create policy "public_insert_propositions"
on public.propositions
for insert
to anon
with check (statut = 'en_attente');

-- Un utilisateur connecté à Supabase peut consulter et gérer les propositions.
drop policy if exists "admin_read_propositions" on public.propositions;
create policy "admin_read_propositions"
on public.propositions
for select
to authenticated
using (true);

drop policy if exists "admin_update_propositions" on public.propositions;
create policy "admin_update_propositions"
on public.propositions
for update
to authenticated
using (true)
with check (true);

drop policy if exists "admin_delete_propositions" on public.propositions;
create policy "admin_delete_propositions"
on public.propositions
for delete
to authenticated
using (true);

-- Aucun SELECT public n'est autorisé : les visiteurs ne peuvent donc pas lire les propositions.
